### ISSUE TITLE
Add support for Gnosis Safe 1.1.0

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-relay-service#160]
The audit for the new contract will be finished soon and we should make the required adjustments in the backend

### TODOs

- [ ] update mater copy address
- [ ] update proxy factory address
- [ ] create new endpoint to create a Safe with fallback manager
- [ ] add support for eth_sign signatures (see #158)

### Notes

- No adjustments required in the normal transaction submission request
